import type { Metadata } from "next";
import { Suspense } from "react";
import HeaderNav from "@/components/HeaderNav";
import "./globals.css";

export const metadata: Metadata = {
  title: "F1 Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-neutral-950 text-neutral-100">
        <div className="min-h-screen flex flex-col">
          <header className="border-b border-neutral-800 bg-neutral-900/80 backdrop-blur">
            <div className="max-w-5xl mx-auto flex items-center justify-between p-4">
              <h1 className="font-semibold tracking-wide text-red-500">
                F1 Dashboard
              </h1>
              <Suspense fallback={<div>Loading...</div>}>
                <HeaderNav />
              </Suspense>
            </div>
          </header>
          <main className="flex-1 max-w-5xl mx-auto w-full p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
